name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  super_bullet_list: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Halcom
    fonts:
      - asset: fonts/Halcom-Black.otf
      - asset: fonts/Halcom-Bold.otf
      - asset: fonts/Halcom-ExtraBold.otf
      - asset: fonts/Halcom-Medium.otf
      - asset: fonts/Halcom-Regular.otf

  assets:
    - images/

